fix: remove install step

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -139,59 +139,59 @@ jobs:
           path: export
           retention-days: 1
 
-  install:
-    needs: [docker-build]
-    runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        os:
-          - ubuntu-24.04
-      fail-fast: false
-    steps:
-      - uses: actions/checkout@v4
+  # install:
+  #   needs: [docker-build]
+  #   runs-on: ${{ matrix.os }}
+  #   strategy:
+  #     matrix:
+  #       os:
+  #         - ubuntu-24.04
+  #     fail-fast: false
+  #   steps:
+  #     - uses: actions/checkout@v4
 
-      - uses: actions/checkout@v4
-        with:
-          repository: pantos-io/ethereum-contracts
-          path: ethereum-contracts
-          sparse-checkout: |
-           Makefile
-           docker-compose.yml
-           docker-compose.ci.yml
-           docker-compose.local.yml
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         repository: pantos-io/ethereum-contracts
+  #         path: ethereum-contracts
+  #         sparse-checkout: |
+  #          Makefile
+  #          docker-compose.yml
+  #          docker-compose.ci.yml
+  #          docker-compose.local.yml
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-        id: buildx
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v3
+  #       id: buildx
 
-      - name: Check docker config and disable live reload
-        run: |
-          echo '{ "live-restore": false }' | sudo tee /etc/docker/daemon.json
-          sudo systemctl reload docker
-          make check-swarm-init
+  #     - name: Check docker config and disable live reload
+  #       run: |
+  #         echo '{ "live-restore": false }' | sudo tee /etc/docker/daemon.json
+  #         sudo systemctl reload docker
+  #         make check-swarm-init
 
-      - name: Run Docker
-        run: |
-          make docker-local
-        working-directory: ethereum-contracts
-        env:
-          DOCKER_TAG: "development"
+  #     - name: Run Docker
+  #       run: |
+  #         make docker-local
+  #       working-directory: ethereum-contracts
+  #       env:
+  #         DOCKER_TAG: "development"
 
-      - name: Ensure ethereum-contracts is accessible
-        run: |
-          for port in 8511 8510; do
-            echo "Checking availability of http://localhost:$port..."
-            for i in {1..30}; do
-              if curl -s --max-time 5 http://localhost:$port/ -X POST -H "Content-Type: application/json" --data '{"method":"eth_blockNumber","params":[],"id":1,"jsonrpc":"2.0"}'; then
-                echo " ... http://localhost:$port is accessible."
-                break
-              else
-                echo "http://localhost:$port is not accessible. Retrying in 10 seconds..."
-                sleep 10
-              fi
-            done
-          done
-        working-directory: ethereum-contracts
+  #     - name: Ensure ethereum-contracts is accessible
+  #       run: |
+  #         for port in 8511 8510; do
+  #           echo "Checking availability of http://localhost:$port..."
+  #           for i in {1..30}; do
+  #             if curl -s --max-time 5 http://localhost:$port/ -X POST -H "Content-Type: application/json" --data '{"method":"eth_blockNumber","params":[],"id":1,"jsonrpc":"2.0"}'; then
+  #               echo " ... http://localhost:$port is accessible."
+  #               break
+  #             else
+  #               echo "http://localhost:$port is not accessible. Retrying in 10 seconds..."
+  #               sleep 10
+  #             fi
+  #           done
+  #         done
+  #       working-directory: ethereum-contracts
 
       # - name: Download artifact
       #   uses: actions/download-artifact@v4
@@ -208,105 +208,105 @@ jobs:
       #     echo 'pantos-service-node-full pantos/common/start_services boolean true' | sudo debconf-set-selections;
 
       # Recover the key used for the ethereum contracts
-      - name: Download artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: signer-key
-          path: ./signer_key.pem
+      # - name: Download artifact
+      #   uses: actions/download-artifact@v4
+      #   with:
+      #     name: signer-key
+      #     path: ./signer_key.pem
 
-      - name: Copy files from eth-data and bnb-data
-        run: |
-          sudo mkdir -p /etc/pantos
-          sudo chmod 777 /etc/pantos
-          # Get the task ID for the eth service
-          ETH_TASK_ID=$(docker ps --filter "name=stack-ethereum-contracts--1-eth" --format "{{.ID}}")
-          # Copy files from the eth service
-          docker cp $ETH_TASK_ID:/data/keystore /etc/pantos/keystore.eth
-          docker cp $ETH_TASK_ID:/data/ETHEREUM.env /etc/pantos/ETHEREUM.env
-          cat /etc/pantos/ETHEREUM.env
+      # - name: Copy files from eth-data and bnb-data
+      #   run: |
+      #     sudo mkdir -p /etc/pantos
+      #     sudo chmod 777 /etc/pantos
+      #     # Get the task ID for the eth service
+      #     ETH_TASK_ID=$(docker ps --filter "name=stack-ethereum-contracts--1-eth" --format "{{.ID}}")
+      #     # Copy files from the eth service
+      #     docker cp $ETH_TASK_ID:/data/keystore /etc/pantos/keystore.eth
+      #     docker cp $ETH_TASK_ID:/data/ETHEREUM.env /etc/pantos/ETHEREUM.env
+      #     cat /etc/pantos/ETHEREUM.env
 
-          # Get the task ID for the bnb service
-          BNB_CHAIN_TASK_ID=$(docker ps --filter "name=stack-ethereum-contracts--1-bnb" --format "{{.ID}}")
-          # Copy files from the bnb service
-          docker cp $BNB_CHAIN_TASK_ID:/data/keystore /etc/pantos/keystore.bnb
-          docker cp $BNB_CHAIN_TASK_ID:/data/BNB_CHAIN.env /etc/pantos/BNB_CHAIN.env
-          cat /etc/pantos/BNB_CHAIN.env
-        working-directory: ethereum-contracts
+      #     # Get the task ID for the bnb service
+      #     BNB_CHAIN_TASK_ID=$(docker ps --filter "name=stack-ethereum-contracts--1-bnb" --format "{{.ID}}")
+      #     # Copy files from the bnb service
+      #     docker cp $BNB_CHAIN_TASK_ID:/data/keystore /etc/pantos/keystore.bnb
+      #     docker cp $BNB_CHAIN_TASK_ID:/data/BNB_CHAIN.env /etc/pantos/BNB_CHAIN.env
+      #     cat /etc/pantos/BNB_CHAIN.env
+      #   working-directory: ethereum-contracts
 
-      - name: Set env
-        run: |
-          sudo cp ./service-node-config.local.env /etc/pantos/service-node-config.env
-          # Append the new addresses from the copied env files
-          sudo cat /etc/pantos/ETHEREUM.env | sudo tee -a /etc/pantos/service-node-config.env > /dev/null
-          sudo cat /etc/pantos/BNB_CHAIN.env | sudo tee -a /etc/pantos/service-node-config.env > /dev/null
-          sudo chmod 644 /etc/pantos/service-node-config.env
-          mv /etc/pantos/service-node-config.env service-node-config.docker.env
+      # - name: Set env
+      #   run: |
+      #     sudo cp ./service-node-config.local.env /etc/pantos/service-node-config.env
+      #     # Append the new addresses from the copied env files
+      #     sudo cat /etc/pantos/ETHEREUM.env | sudo tee -a /etc/pantos/service-node-config.env > /dev/null
+      #     sudo cat /etc/pantos/BNB_CHAIN.env | sudo tee -a /etc/pantos/service-node-config.env > /dev/null
+      #     sudo chmod 644 /etc/pantos/service-node-config.env
+      #     mv /etc/pantos/service-node-config.env ./service-node-config.docker.env
 
-      - name: Run Service Node Docker
-        run: |
-          make docker
-        env:
-          DEV_MODE: "false"
+      # - name: Run Service Node Docker
+      #   run: |
+      #     make docker
+      #   env:
+      #     DEV_MODE: "true"
 
-      # Check service is running
-      - name: Check service is running
-        timeout-minutes: 5
-        run: |
-          max_retries=180
-          retries=0
-          set +e
-          while [ $retries -lt $max_retries ]; do
-            response=$(curl -s --max-time 5 -o /dev/null -w '%{http_code}' 'http://localhost:8080/bids?source_blockchain=0&destination_blockchain=1')
-            exit_code=$?
-            if [ "$response" -eq 200 ]; then
-              echo "Received 200 response, exiting."
-              break
-            elif [ $exit_code -eq 28 ]; then
-              echo "Curl timed out, continuing to retry."
-            else
-              echo "Did not receive 200 response, retrying in 1 second."
-            fi
-            sleep 1
-            retries=$((retries + 1))
-          done
-          set -e
-          if [ $retries -eq $max_retries ]; then
-            echo "Max retries reached, exiting with failure."
-            exit 1
-          fi
-          echo "Service is up and running"
+      # # Check service is running
+      # - name: Check service is running
+      #   timeout-minutes: 5
+      #   run: |
+      #     max_retries=180
+      #     retries=0
+      #     set +e
+      #     while [ $retries -lt $max_retries ]; do
+      #       response=$(curl -s --max-time 5 -o /dev/null -w '%{http_code}' 'http://localhost:8080/bids?source_blockchain=0&destination_blockchain=1')
+      #       exit_code=$?
+      #       if [ "$response" -eq 200 ]; then
+      #         echo "Received 200 response, exiting."
+      #         break
+      #       elif [ $exit_code -eq 28 ]; then
+      #         echo "Curl timed out, continuing to retry."
+      #       else
+      #         echo "Did not receive 200 response, retrying in 1 second."
+      #       fi
+      #       sleep 1
+      #       retries=$((retries + 1))
+      #     done
+      #     set -e
+      #     if [ $retries -eq $max_retries ]; then
+      #       echo "Max retries reached, exiting with failure."
+      #       exit 1
+      #     fi
+      #     echo "Service is up and running"
 
-      - name: Print logs
-        if: always()
-        run: |
-          # Print the contents of every file in /var/log/pantos
-          sudo find /var/log/pantos -type f -exec sudo cat {} \;
+      # - name: Print logs
+      #   if: always()
+      #   run: |
+      #     # Print the contents of every file in /var/log/pantos
+      #     sudo find /var/log/pantos -type f -exec sudo cat {} \;
 
-      - name: Fix permissions for upload
-        if: always()
-        run: |
-          sudo chmod -R 777 /var/log/pantos
-          sudo chmod -R 777 /etc/pantos
+      # - name: Fix permissions for upload
+      #   if: always()
+      #   run: |
+      #     sudo chmod -R 777 /var/log/pantos
+      #     sudo chmod -R 777 /etc/pantos
 
-      - name: Upload logs
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: install-logs-${{ matrix.os }}
-          path: /var/log/pantos
+      # - name: Upload logs
+      #   if: always()
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: install-logs-${{ matrix.os }}
+      #     path: /var/log/pantos
 
-      - name: Upload env config
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: env-config-${{ matrix.os }}
-          path: /etc/pantos
+      # - name: Upload env config
+      #   if: always()
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: env-config-${{ matrix.os }}
+      #     path: /etc/pantos
 
-      - name: Dump ethereum contract logs
-        if: always()
-        run: |
-          timeout 1 make docker-logs || true
-        working-directory: ethereum-contracts
+      # - name: Dump ethereum contract logs
+      #   if: always()
+      #   run: |
+      #     timeout 1 make docker-logs || true
+      #   working-directory: ethereum-contracts
 
   e2e-tests:
     name: E2E tests
